apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo8
  name: demo8
spec:
  ports:
  - name: "8081"
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: demo8
  type: ClusterIP
status:
  loadBalancer: {}
